name: Deploy Static Website to Hostico

on:
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  web-deploy:
    name: Deploying to Hostico
    runs-on: ubuntu-latest
    steps:
      - name: Get latest code
        uses: actions/checkout@v4

      - name: Sync files to Hostico via FTPS
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          protocol: ftps
          port: 21
          local-dir: ./public_html/
          server-dir: public_html/
          exclude: |
            **/.git*
            **/.git*/**
            README.md
            .github/**
